import { readdirSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import process from 'node:process'

// One-off generator: emits the official Drizzle schema for Better Auth's core
// tables straight from the live auth instance, so the schema can never drift
// from the options the app actually runs. Re-run after changing auth options
// or adding a plugin:
//   pnpm exec jiti scripts/generate-auth-schema.mts
// Equivalent to `npx @better-auth/cli generate --output server/db/schema/auth.ts`,
// but sourced from the installed adapter (1.7.x) instead of the stale CLI package.

const HEADER = `// Generated by Better Auth's Drizzle schema generator (scripts/generate-auth-schema.mts),
// sourced from the live auth instance in server/auth.ts so the tables can never drift
// from what the adapter expects. Re-run the script after changing auth options/plugins.
`

process.loadEnvFile('.env')

const adapterDist = new URL('../node_modules/@better-auth/drizzle-adapter/dist/', import.meta.url)
const generatorFile = readdirSync(adapterDist).find(file => file.startsWith('generate-drizzle-schema-'))
if (!generatorFile) {
  throw new Error('generate-drizzle-schema bundle not found in @better-auth/drizzle-adapter/dist')
}

const { generateDrizzleSchema } = await import(new URL(generatorFile, adapterDist).href)
const { auth } = await import('../server/auth.ts')
const { options, tables } = await auth.$context

const output = new URL('../server/db/schema/auth.ts', import.meta.url)
const { code } = await generateDrizzleSchema({
  options,
  tables,
  provider: 'pg',
  camelCase: true,
})
// The generator emits:
// - a relations block built on `defineRelationsPart`, which only exists in
//   drizzle-orm 1.0 rc (this repo pins stable 0.45.x). Nothing reads auth
//   relations, so strip the block and its import.
// - naive `timestamp` columns; keep `withTimezone: true` to match the existing
//   Postgres columns and preserve timezone correctness for pg.
// - string-named columns (`text("accountId")`); rewrite them to property-key form
//   (`accountId: text()`) so drizzle's global `casing: 'snake_case'` maps them to
//   snake_case DB columns, and so the adapter can look columns up by Better Auth's
//   camelCase field names at runtime.
const stripped = code
  .replace('import { defineRelationsPart } from "drizzle-orm";\n', '')
  .replace(/\nexport const authRelations = defineRelationsPart\([\s\S]*$/, '\n')
  .replace(/(\w+): (text|timestamp|boolean|integer|bigint|jsonb|uuid)\("([A-Za-z]\w*)"\)/g, '$1: $2()')
  .replace(/timestamp\(\)/g, 'timestamp({ withTimezone: true })')
await writeFile(output, HEADER + stripped)
console.log(`Wrote ${output.pathname}`)
process.exit(0)
